import { Link } from 'react-router-dom'
import {
  FileLock2, ShieldCheck, ArrowRight, Workflow, Lock, AlertTriangle,
  FileCheck2, Sparkles, ListChecks,
} from 'lucide-react'
import { PageHeader, PageBody } from '../../components/layout/PageHeader'
import { Card, Button, Badge } from '../../components/ui'

/**
 * InvoiceManagerPlaceholder — protected module entry.
 * P1 polish: matches the new shell + clearer messaging about sequencing
 * (Portal first → harmonize Manager later).
 */
export default function InvoiceManagerPlaceholder() {
  return (
    <>
      <PageHeader
        title="Invoice Manager — Admin Only"
        description="Existing verified billing module — visually integrated in the future, source untouched today."
      />

      <PageBody>
        <Card padding="lg" className="border-amber-200 bg-gradient-to-br from-white via-amber-50/40 to-white">
          <div className="flex flex-col lg:flex-row items-start gap-6">
            <div className="w-16 h-16 rounded-2xl bg-amber-100 text-amber-800 flex items-center justify-center shrink-0 shadow-card">
              <FileLock2 className="w-8 h-8" />
            </div>
            <div className="flex-1">
              <div className="inline-flex items-center gap-1.5 px-2.5 py-1 rounded-full bg-amber-100 border border-amber-200 text-amber-900 text-[11px] font-semibold uppercase tracking-wider">
                <Lock className="w-3 h-3" /> Protected Module
              </div>
              <h2 className="mt-3 text-xl sm:text-2xl font-bold text-ink-900">Existing Verified Invoice Manager</h2>
              <p className="mt-2 text-sm text-ink-600 max-w-2xl leading-relaxed">
                the owner's existing local Invoice Manager (Python · SQLite · ReportLab) remains the single source of truth for editing invoices generated by Claude.
                It is not embedded in this prototype. It is not connected, iframed, or restyled. Its source files, database, and PDF engines are untouched.
              </p>

              <div className="mt-5 grid grid-cols-1 sm:grid-cols-2 gap-3">
                <Feature
                  icon={Workflow}
                  title="Where it fits in the product"
                  body="In the unified Admin application, this module will live behind a single nav entry next to Cases Master and Daily Report — using the same design language and the same role gating shown throughout this prototype."
                />
                <Feature
                  icon={ShieldCheck}
                  title="What stays protected"
                  body="The verified Manager baseline — server.py, db.py, pdf_gen.py, calc.py, the static UI, and the local hmc_manager.db — is not modified by P0 or P1, and will not be modified without a separate approved sprint."
                />
                <Feature
                  icon={FileCheck2}
                  title="What is in the Portal instead"
                  body="The Admin Case Detail records the invoice result manually after the owner uses Claude / Manager. There is no Generate Invoice button in the Portal and no PDF generation runs here."
                />
                <Feature
                  icon={ListChecks}
                  title="Sequencing"
                  body="Portal workflows, fields, and reports are approved first (this sprint and the next). Only then is a dedicated approved sprint launched to visually harmonize the Manager, never to change its billing engines."
                />
              </div>

              <div className="mt-6 rounded-xl border border-border bg-white p-4">
                <div className="flex items-start gap-2.5">
                  <div className="w-8 h-8 rounded-lg bg-sky-50 text-sky-700 flex items-center justify-center shrink-0">
                    <Sparkles className="w-4 h-4" />
                  </div>
                  <div>
                    <div className="text-sm font-semibold text-ink-900">Future integration concept</div>
                    <p className="mt-1 text-xs text-ink-600 leading-relaxed">
                      When the dedicated Manager-UX sprint is approved, the experience should feel like a single professional product:
                      same sidebar, same colors, same status vocabulary used here. Today, this card is the bridge —
                      a clear signpost in the Admin workspace that says <span className="font-semibold text-ink-900">“Invoice Manager lives here, when ready.”</span>
                    </p>
                  </div>
                </div>
              </div>

              <div className="mt-5 flex flex-wrap items-center gap-2">
                <Badge tone="warning"><Lock className="w-3 h-3" /> No iframe</Badge>
                <Badge tone="warning"><Lock className="w-3 h-3" /> No direct link</Badge>
                <Badge tone="warning"><Lock className="w-3 h-3" /> No restyling</Badge>
                <Badge tone="warning"><Lock className="w-3 h-3" /> No source modification</Badge>
                <Badge tone="warning"><Lock className="w-3 h-3" /> No PDF execution</Badge>
              </div>

              <div className="mt-6 flex flex-col sm:flex-row items-stretch sm:items-center gap-2">
                <Button as={Link} to="/admin/dashboard" rightIcon={<ArrowRight className="w-4 h-4" />} variant="secondary">Back to Admin Dashboard</Button>
                <Button as={Link} to="/admin/cases" rightIcon={<ArrowRight className="w-4 h-4" />} variant="ghost">Open Cases Master</Button>
              </div>
            </div>
          </div>
        </Card>

        <div className="rounded-lg bg-emerald-50 border border-emerald-100 p-3 text-xs text-emerald-900 flex items-start gap-2">
          <ShieldCheck className="w-4 h-4 mt-0.5 shrink-0 text-emerald-700" />
          <div>
            Clinic users do not see this nav entry — gated by role context. Confirmed by the role-based navigation in <span className="font-mono">Sidebar.jsx</span> and <span className="font-mono">MobileTopBar.jsx</span>.
          </div>
        </div>
      </PageBody>
    </>
  )
}

function Feature({ icon: Icon, title, body }) {
  return (
    <div className="rounded-lg border border-border bg-white p-3.5">
      <div className="flex items-start gap-2.5">
        <div className="w-8 h-8 rounded-md bg-navy-50 text-navy-700 flex items-center justify-center shrink-0">
          <Icon className="w-4 h-4" />
        </div>
        <div>
          <div className="text-sm font-semibold text-ink-900">{title}</div>
          <div className="text-xs text-ink-600 mt-1 leading-relaxed">{body}</div>
        </div>
      </div>
    </div>
  )
}
